version: 1.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
    - gh-pages

environment:
  matrix:

    - platform: x86
      QTDIR: C:\Qt\5.7\msvc2015

    - platform: x64
      QTDIR: C:\Qt\5.7\msvc2015_64

build:
  project: GLoSC.sln
  verbosity: normal

after_build:
  - 7z a GloSC_%platform%.zip TargetConfig.ini

artifacts:
  - path: GLoSC_$(platform).zip
    name: GLoSC_$(platform)

deploy:

  - provider: GitHub
    description: 'Would be nice to auto-generate this...'
    artifact: /GLoSC_x..\.zip/
    auth_token:
      secure: Ec0RLkIirpuLD2eNfFlN51Jsxv737ZVX9kcwNlxSBd8A/eTn/uYvpN/nAMctsHUq
    force_update: true
    on:
      appveyor_repo_tag: true

