version: 1.2.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
environment:
  matrix:
#  - platform: x86
#    QTDIR: C:\Qt\5.9\msvc2017
#    OUTNAME: Win32
  - platform: x64
    QTDIR: C:\Qt\5.9\msvc2017_64
    OUTNAME: x64
build:
  project: GloSC.sln
  verbosity: normal
after_build:
- cmd: >-
    7z a GloSC_%platform%.zip TargetConfig.ini License.txt qt-license.txt Readme.md Build_Install.md %APPVEYOR_BUILD_FOLDER%\build\%OUTNAME%\%configuration%\*.exe %APPVEYOR_BUILD_FOLDER%\build\Win32Only\%configuration%\*.exe %APPVEYOR_BUILD_FOLDER%\build\Win32Only\%configuration%\*.dll %APPVEYOR_BUILD_FOLDER%\dependencies\SFML-2.4.2-%platform%\bin\sfml-system-2.dll %APPVEYOR_BUILD_FOLDER%\dependencies\SFML-2.4.2-%platform%\bin\sfml-window-2.dll %APPVEYOR_BUILD_FOLDER%\dependencies\SFML-2.4.2-%platform%\bin\sfml-graphics-2.dll redist\* %QTDIR%\bin\Qt5Core.dll %QTDIR%\bin\Qt5Gui.dll %QTDIR%\bin\Qt5Widgets.dll %QTDIR%\plugins\platforms\qwindows.dll


    7z rn GloSC_%platform%.zip qwindows.dll platforms\qwindows.dll
artifacts:
- path: GloSC_$(platform).zip
  name: GloSC_$(platform)
deploy:
- provider: GitHub
  auth_token:
    secure: HdTPh2HVHhlpsjWkSIT89w+4KyDeB9CVCb/FFlzZpYdUTtUqLSAJ5/nOw29be0PG
  artifact: /GloSC_x..\.zip/
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master