version: 2.0.6.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
environment:
  matrix:
  - platform: x86
    QTDIR: C:\Qt\5.13.1\msvc2017
    OUTNAME: Win32
build:
  project: GloSC.sln
  verbosity: normal