version: 1.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
    - gh-pages

environment:
  matrix:

    - platform: x86
      QTDIR: C:\Qt\5.7\msvc2015
      OUTNAME: Win32

    - platform: x64
      QTDIR: C:\Qt\5.7\msvc2015_64
      OUTNAME: x64

build:
  project: GLoSC.sln
  verbosity: normal

after_build:
  - "7z a GloSC_%platform%.zip
      TargetConfig.ini
      %APPVEYOR_BUILD_FOLDER%\build\%OUTNAME%\%configuration%\*
      %APPVEYOR_BUILD_FOLDER%\build\Win32Only\%configuration%\*
      %APPVEYOR_BUILD_FOLDER%\dependencies\SFML-2.4.1-$(platform)\bin
      %APPVEYOR_BUILD_FOLDER%\dependencies\ViGEmUM\$(platform)\bin"

artifacts:
  - path: GLoSC_$(platform).zip
    name: GLoSC_$(platform)

deploy:

  - provider: GitHub
    description: 'Would be nice to auto-generate this...'
    artifact: /GLoSC_x..\.zip/
    auth_token:
      secure: Ec0RLkIirpuLD2eNfFlN51Jsxv737ZVX9kcwNlxSBd8A/eTn/uYvpN/nAMctsHUq
    force_update: true
    on:
      appveyor_repo_tag: true

