version: 1.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  except:
    - gh-pages

environment:
  matrix:

    - platform: x86
      QTDIR: C:\Qt\5.7\msvc2015

    - platform: x64
      QTDIR: C:\Qt\5.7\msvc2015_64

build:
  project: GLoSC.sln
  verbosity: normal

artifacts:
  - TargetConfig.ini

deploy:

  - provider: GitHub
    auth_token:
      secure: Ec0RLkIirpuLD2eNfFlN51Jsxv737ZVX9kcwNlxSBd8A/eTn/uYvpN/nAMctsHUq
    on:
      appveyor_repo_tag: true

